CREATE TABLE IF NOT EXISTS delegated_admins (
    github_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    granted_by BIGINT UNSIGNED NOT NULL,
    granted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
